- name: check if nginx config exists 
  stat: path=/etc/nginx/nginx.conf
  register: st

- name: install nginx package 
  apt:
   name: nginx
   state: present 
   update_cache: yes
  when: not st.stat.exists
