---

# Add vagrant user to the suoers file and just about the line "User privilege specification". Allow vagrant user to sudo without b# eing prompted for password

- name: update sudoers file for vagrant user 
  lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^vagrant\s'
   insertafter: '^# User privilege specification'
   line: 'vagrant ALL=(ALL) NOPASSWD: ALL'
   validate: '/usr/sbin/visudo -cf %s'

# Update admin group in sudoers file and enforce users in this group to add password

- name: update sudoers file for admin group
  lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%ADMIN ALL='
   line: '%ADMIN ALL=(ALL) ALL'
   validate: '/usr/sbin/visudo -cf %s'
