---
# tasks file for php
- name: install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
      - git
      - mcrypt
      - php5-cli
      - php5-curl
      - php5-fpm
      - php5-intl
      - php5-json
      - php5-mcrypt
      - php5-sqlite
      - sqlite3

- name: ensure php5-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
     - restart php5-fpm
     - restart nginx

- name: enable php5 mcrypt module
  shell: php5enmod mcrypt
  args:
     creates: /etc/php5/cli/conf.d/20-mcrypt.ini

- name: copy a updated version of php default sites config 
  template: src=default.j2 dest="/etc/nginx/sites-available/default"
  notify: restart php5-fpm 

- name: Clone git repository and deploy php code
  git: >
    dest=/usr/share/nginx/html/al
    repo=https://github.com/philiphorrocks/al_test.git
    update=no
  become: yes
  sudo_user: www-data


- name: confirm URL is available (helloworld.php) 
  uri:
    url: "http://localhost:80/al/helloworld.php"
    status_code: 200
    validate_certs: False
  register: result
  until: result | succeeded
  retries: 8
  delay: 20
